### ISSUE TITLE
Version number is missing

### ISSUE THREAD

**Issue by pablobm** [dokku/dokku-update#23]
The current script doesn't have a value for `DOKKU_UPDATE_VERSION`. As a result, the `version` command doesn't work:

```
$ ./dokku-update version
dokku-update 
```

The offending line:

https://github.com/dokku/dokku-update/blob/ad85e842797f0b2ca60ed51fa49e4256fc234436/dokku-update#L38

I have tried running the Makefile locally and it does generate the above line correctly for me, so the problem must be in the environment where the committed version was run.

**Comment by josegonzalez** [comment]
This should be fixed if you install the file from the debian package. Thanks for reporting.
