### ISSUE TITLE
Update of Dokku :  Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by g-normand** [dokku/dokku-update#43]
## Description of problem

I have an old Dokku (0.23.8) on Ubuntu 20.04

I want to upgrade it 

> dokku-update version
dokku-update  0.7.2

but when I run "dokku-update run"
> -----> Updating Dokku
E: Unable to correct problems, you have held broken packages.

What could be the problem? I don't have any problem when I do "apt upgrade" or "apt update" ?

**Comment by josegonzalez** [comment]
Try running:

sudo apt install -y dokku

**Comment by g-normand** [comment]
apt install -y dokku
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dokku : Depends: docker-compose-plugin but it is not installable or
                  moby-compose but it is not installable
E: Unable to correct problems, you have held broken packages


That was the problem, thanks @josegonzalez !
